### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Spieny** [java-deobfuscator/deobfuscator-gui#14]
loading classpath...
``Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at com.javadeobfuscator.org.objectweb.asm.tree.MethodNode.visitInsn(MethodNode.java:423)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readCode(ClassReader.java:1466)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1126)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:698)
	at com.javadeobfuscator.org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspathFile(Deobfuscator.java:94)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadClasspath(Deobfuscator.java:113)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

**OK,now I fixed this error by myself**
I changed
" builder.append("java -jar deobfuscator.jar"); "
to
" builder.append("java -Xms1024m -Xmx1024m -jar deobfuscator.jar"); "
in the src.

**Comment by ThisTestUser** [comment]
You should be able to run -Xms and -Xmx on the deobfuscator gui itself to add memory.
