### ISSUE TITLE
Error when deobfuscating, how to handle

### ISSUE THREAD

**Issue by fpb1386** [java-deobfuscator/deobfuscator-gui#18]
The output of deobfucator-gui.jar
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading classpath
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Loading input
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Computing callers
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Transforming
[Thread-6] INFO com.javadeobfuscator.deobfuscator.Deobfuscator - Writing

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.io.FileNotFoundException: 
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

How to handle these problems?

**Comment by ThisTestUser** [comment]
Did you select the file correctly?

**Comment by CauaJ19** [comment]
I selected the file correctly but still giving this error.

**Comment by ThisTestUser** [comment]
Use my deobfuscator: https://github.com/ThisTestUser/deobfuscator/releases
