### ISSUE TITLE
java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by gbyczyns** [java-deobfuscator/deobfuscator-gui#19]
Pressing the 'Run' button causes the following exception:
```java
java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2417)
	at com.javadeobfuscator.deobfuscator.ui.util.Reflect.setFieldO(Reflect.java:124)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Config.setTransformers(Config.java:34)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:809)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

Problematic line is:
```Field acc = Field.class.getDeclaredField("modifiers");```

My config:
```openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+32)
OpenJDK 64-Bit Server VM (build 12+32, mixed mode, sharing)

Distributor ID:	LinuxMint
Description:	Linux Mint 19.1 Tessa
Release:	19.1
Codename:	tessa
```

**Comment by gbyczyns** [comment]
Looks like using reflection is not a good idea, since dropping 'final' modifier is no longer possible with JDK 12.

**Comment by ThisTestUser** [comment]
You would have to run the GUI with Java 11 or below, or just use the yml config to run the deobfuscator then.

**Comment by davidrochin** [comment]
Solution?

**Comment by ThisTestUser** [comment]
Should be fixed in the latest release.

**Comment by Giovanniz24** [comment]
vgcggc
