### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by LIWKK** [java-deobfuscator/deobfuscator-gui#27]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(Unknown Source)
	at java.lang.StringBuilder.<init>(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.map(CustomRemapper.java:140)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.CustomRemapper.mapFieldName(CustomRemapper.java:95)
	at org.objectweb.asm.commons.MethodRemapper.visitFieldInsn(MethodRemapper.java:119)
	at org.objectweb.asm.tree.FieldInsnNode.accept(FieldInsnNode.java:101)
	at org.objectweb.asm.tree.InsnList.accept(InsnList.java:162)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:817)
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:727)
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.lambda$0(AbstractNormalizer.java:47)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer$$Lambda$22/89761232.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.normalizer.AbstractNormalizer.transform(AbstractNormalizer.java:42)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:409)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:366)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.lang.Thread.run(Unknown Source)

How can i add more memory to this, i have 16GB DDR4

**Comment by ThisTestUser** [comment]
Please report issues in the deobfuscator project next time (https://github.com/java-deobfuscator/deobfuscator/issues).
To add more memory, launch the GUI with the xmx arguments (java -jar deobfuscator-gui.jar -Xmx). If it still doesn't work, you may have to use another tool to rename the files.
