### ISSUE TITLE
getting 'java.lang.NoClassDefFoundError' error

### ISSUE THREAD

**Issue by IamSanjid** [java-deobfuscator/deobfuscator-gui#35]
`Exception in thread "main" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
        at com.javadeobfuscator.deobfuscator.ui.component.SynchronousJFXCaller.init(SynchronousJFXCaller.java:28)
        at com.javadeobfuscator.deobfuscator.ui.SwingWindow.main(SwingWindow.java:64)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 2 more`
Any suggestion what should i do?

**Comment by Janmm14** [comment]
The gui requires you to have javafx installed. Not every java distribution has this included.
For example the Zulu OpenJDK distribution does have packages with javafx. Install that one

**Comment by IamSanjid** [comment]
> The gui requires you to have javafx installed. Not every java distribution has this included.
> For example the Zulu OpenJDK distribution does have packages with javafx. Install that one

![image](https://user-images.githubusercontent.com/38256064/123839580-17262c00-d92f-11eb-8862-bfd2dd983f36.png)
Ah i guess i should download the latest version?

**Comment by Janmm14** [comment]
you need the non-headless version of it

**Comment by ThisTestUser** [comment]
It looks like this issue has been resolved, so I'm going to close this. I don't think there are any issues with different versions or installations of Java currently.
