### ISSUE TITLE
Java-deobfuscator-GUI-Error

### ISSUE THREAD

**Issue by nanzerrous** [java-deobfuscator/deobfuscator-gui#42]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.ArithmeticException: / by zero
	at com.javadeobfuscator.deobfuscator.transformers.smoke.NumberObfuscationTransformer.doMath(NumberObfuscationTransformer.java:135)
	at com.javadeobfuscator.deobfuscator.transformers.smoke.NumberObfuscationTransformer.transform(NumberObfuscationTransformer.java:83)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Its not an error of the gui itself.
Please create the issue over at the deobfuscator project.
