### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by paidmodcracks** [java-deobfuscator/deobfuscator-gui#47]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1529)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1491)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:721)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at com.javadeobfuscator.javavm.VirtualMachine.load(VirtualMachine.java:1016)
	at com.javadeobfuscator.javavm.VirtualMachine.<init>(VirtualMachine.java:121)
	at com.javadeobfuscator.deobfuscator.utils.TransformerHelper.newVirtualMachine(TransformerHelper.java:269)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:36)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$$Lambda$87/24850541.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

I have tried changing the java heap size from in control panel (tried 4096m and 8192m and got same error with both)

**Comment by Janmm14** [comment]
@paidmodcracks 
Please open this issue again in the deobfuscator repository. Issues here should be for the GUI only.

And - as your name hints at it - make sure to not post copyrighted files adn do not link to unofficial places where to find those.

In general I would recommend the other allatori StringEncryptionTransformer (the one without `string.`)
