### ISSUE TITLE
Deobfuscation failed. Please open a ticket on GitHub

### ISSUE THREAD

**Issue by ghost** [java-deobfuscator/deobfuscator-gui#51]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unknown action for encrypted strings array
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:1301)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:977)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:478)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:435)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:74)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$15$1.run(SwingWindow.java:812)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Janmm14** [comment]
Wrong repository. This is for problems about hte user interface, not about the deobfuscation process.
Go here please: https://github.com/java-deobfuscator/deobfuscator/issues

Also we will ot be able to fix your issue if yo uare not allowed to upload the input file.
We do not operate if you are not allowed to share or link to where the input file is available legally, see https://github.com/java-deobfuscator/deobfuscator/issues/653
