### ISSUE TITLE
Error say me to open ticket here

### ISSUE THREAD

**Issue by FloppaAirlines** [java-deobfuscator/deobfuscator-gui#54]
Hello, i try to deobf Rise client and say me this error : 

Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.RuntimeException: Unexpected opcode! Mode 0, opcode 167 at rise/ZbXSUuiS87GWoxGvsBI9502368823
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.lambda$transform$25(StringEncryptionTransformer.java:779)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at com.javadeobfuscator.deobfuscator.transformers.zelix.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:114)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)

**Comment by greenozon** [comment]
This is not a GUI error, so you better move your issue over here: https://github.com/java-deobfuscator/deobfuscator/issues
2) as a rule of thumb it's good to attach your input jar to the ticket for upcoming investigation...

**Comment by Janmm14** [comment]
Only attach input when allowed to share the jar or link to original source. When its not available for free / in public, do not attach or link jar.
