### ISSUE TITLE
Deobfuscation failed

### ISSUE THREAD

**Issue by FloppaAirlines** [java-deobfuscator/deobfuscator-gui#55]
com.javadeobfuscator.javavm.exceptions.ExecutionException: Unexpected value: JavaUnknown(type=Ljava/lang/String;,cause=Invocation on net/minecraft/util/StatCollector func_74838_a(Ljava/lang/String;)Ljava/lang/String;)
	at com.javadeobfuscator.javavm.values.JavaWrapper.asObject(JavaWrapper.java:161)
	at com.javadeobfuscator.javavm.VirtualMachine.convertJavaObjectToString(VirtualMachine.java:471)
	at com.javadeobfuscator.deobfuscator.transformers.allatori.string.StringEncryptionTransformer.transform(StringEncryptionTransformer.java:90)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.runFromConfig(Deobfuscator.java:477)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:434)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janmm14** [comment]
Use deobfuscator issues instead of deob GUI issues for that.
In general its adviced to first try transformers without a `.` in name.
