### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by 1341313rqwewqe** [java-deobfuscator/deobfuscator-gui#58]
Deobfuscation failed. Please open a ticket on GitHub and provide the following error:
java.lang.OutOfMemoryError: Java heap space
	at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:127)
	at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:158)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2147)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2102)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2123)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2078)
	at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:721)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.loadInput(Deobfuscator.java:268)
	at com.javadeobfuscator.deobfuscator.Deobfuscator.start(Deobfuscator.java:378)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x0000000800dca000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x0000000800cb1000.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:154)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.run(Deobfuscator.java:84)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$null$17(SwingWindow.java:1009)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$$Lambda$196/0x0000000800d12f78.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Janmm14** [comment]
This is not an issue of the gui, only of the deobfuscator. Create such issues next time in the deobfuscator repository and not in the gui one.

Try increase ram with -Xmx jvm flag.
Maybe your input contains some zip bomb stuff which you'll have to manually delete before using the deobfuscator.
