### ISSUE TITLE
Input and Output buttons dont work on Arch linux(idk if this bug works on other distros)

### ISSUE THREAD

**Issue by master7720** [java-deobfuscator/deobfuscator-gui#61]

**Comment by Janmm14** [comment]
@master7720 
I do not test under linux, but it should be using quite common JavaFX functionality for the file chooser (mainly because on windows the swing file chooser sucks and javafx uses native file chooser).

Weird if that doesn't work.

Please try opening the gui via command line (`java -jar deobfuscator-gui.jar`). Does an error pop up in the console? If yes, pls post it.

**Comment by master7720** [comment]
[notrocky@PewPew ~]$ java -jar '/home/notrocky/Desktop/deobfuscator-gui.jar' 
Searching for deobfuscator in /home/notrocky
com.javadeobfuscator.deobfuscator.ui.util.FallbackException: Could not create Config instance.
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.getConfig(Deobfuscator.java:65)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.loadWrappers(SwingWindow.java:1442)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.access$000(SwingWindow.java:55)
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow$1.run(SwingWindow.java:80)
Caused by: java.lang.NullPointerException
	at com.javadeobfuscator.deobfuscator.ui.wrap.Deobfuscator.getConfig(Deobfuscator.java:61)
	... 3 more
Loading deobfuscator from jar: /home/notrocky/Desktop/deobfuscator.jar
Exception in thread "AWT-EventQueue-0" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: javafx/stage/FileChooser
	at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$main$2(SwingWindow.java:239)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:262)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.NoClassDefFoundError: javafx/stage/FileChooser
	... 37 more
Caused by: java.lang.ClassNotFoundException: javafx.stage.FileChooser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 37 more

**Comment by Janmm14** [comment]
I will add further protection against Nullpointer problems.

Please see issue #43, you are apparantly not using a java installation with inbuilt javafx.

**Comment by Janmm14** [comment]
Version 4.2
The program now checks jfx presense reliably on start again.
Additionally the error messages for not found deobfuscator jar have been improved and the null pointer exception shouldn't happen anymore.
