### ISSUE TITLE
Can't use 'Select' button, throws exception.

### ISSUE THREAD

**Issue by bluegreenblack** [java-deobfuscator/deobfuscator-gui#62]
`Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Toolkit not initialized
       at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.runLater(Unknown Source)
        at javafx.graphics/javafx.application.Platform.runLater(Unknown Source)
        at com.javadeobfuscator.deobfuscator.ui.component.SynchronousJFXCaller.call(SynchronousJFXCaller.java:106)
        at com.javadeobfuscator.deobfuscator.ui.component.SynchronousJFXFileChooser.showDialog(SynchronousJFXFileChooser.java:89)
        at com.javadeobfuscator.deobfuscator.ui.component.SynchronousJFXFileChooser.showDialog(SynchronousJFXFileChooser.java:53)
        at com.javadeobfuscator.deobfuscator.ui.component.SynchronousJFXFileChooser.showOpenDialog(SynchronousJFXFileChooser.java:111)
        at com.javadeobfuscator.deobfuscator.ui.SwingWindow.lambda$main$2(SwingWindow.java:297)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
        at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Unknown Source)
        at java.desktop/java.awt.Container.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

When running .\zulu19.30.11-ca-fx-jre19.0.1-win_x64\bin\java.exe -jar .\deobfuscator-gui.jar

This happens whenever I click either of the two buttons to select a file making them unusable.

java version 19, Windows 10, deobfuscator-gui version 4.2 (latest at the time of this post).

**Comment by Janmm14** [comment]
Looking at it now I wonder how the fuck the program did ever work when I tested it in my IDE, I'M sure I tried the select buttons. The jfx init thread doesn't get called.
Fixed in 4.2.1 - https://github.com/java-deobfuscator/deobfuscator-gui/commit/ea513c7b3a09689b98d800243bd2b0ff524cee71
